FROM python:3.12-slim

WORKDIR /app

COPY transpiler_service/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY transpiler_service/transpiler_service.py transpiler_service.py 

EXPOSE 5002

CMD ["python", "transpiler_service.py"]
